#+title: Oglot Python Example
#+author: Gerard Vermeulen
#+property: header-args:python :tangle rpasyncio.py :comments link

* Setup

The post [[https://realpython.com/async-io-python/][Async IO in Python: A Complete Walkthrough]] is source of the
Python code in Org source blocks.  The setup assumes successful
installation of ~oglot~ and successful execution of the source block
below.

#+begin_src emacs-lisp -n :results silent
(require 'oglot)
#+end_src

The setup also assumes that there is a tangled file [[./rpasyncio.py][rpasyncio.py]] for
the execution of the source block below.

#+begin_src python -i -n :results silent :session :tangle no
from rpasyncio import rp1, rp2, rp3
#+end_src

This opens an inferior Python shell to display the output of the
Python calls ~rp1()~, ~rp2()~, and ~rp3()~ below.  Calling
~org-edit-src-code~ with point on one of the blocks ~rp1~, ~rp2~, or
~rp3~ will open the ~org-src-mode~ buffer in a visually unchanged
identical way while launching Eglot on [[./rpasyncio.py][rpasyncio.py]].

* 1st example

#+name: rp1
#+begin_src python -i -n :results silent :session
# countsync.py example
def rp1():
    import asyncio
    import time

    async def count():
        print("One")
        await asyncio.sleep(1)
        print("Two")

    async def main():
        await asyncio.gather(count(), count(), count())

    tick = time.perf_counter()
    asyncio.run(main())
    ticktock = time.perf_counter() - tick
    print(f"{__name__} executed in {ticktock:0.2f} seconds.")
#+end_src

#+begin_src python -i -n :results silent :session :tangle no
rp1()
#+end_src

* 2nd example

#+caption: ~rand.py~
#+name: rp2
#+begin_src python -i -n :results silent :session
# rand.py example
def rp2(seed):
    import asyncio
    import random

    # ANSI colors
    c = (
        "\033[0m",  # End of color
        "\033[36m",  # Cyan
        "\033[91m",  # Red
        "\033[35m",  # Magenta
    )

    async def makerandom(idx: int, threshold: int = 6) -> int:
        print(c[idx + 1] + f"Initiated makerandom({idx}).")
        i = random.randint(0, 10)
        while i <= threshold:
            print(c[idx + 1] + f"makerandom({idx}) == {i} too low; retrying.")
            await asyncio.sleep(idx + 1)
            i = random.randint(0, 10)
        print(c[idx + 1] + f"---> Finished: makerandom({idx}) == {i}" + c[0])
        return i

    async def main():
        res = await asyncio.gather(*(makerandom(i, 10 - i - 1) for i in range(3)))
        return res

    random.seed(seed)
    r1, r2, r3 = asyncio.run(main())
    print()
    print(f"r1: {r1}, r2: {r2}, r3: {r3}")
#+end_src

#+begin_src python -i -n :results silent :session :tangle no
rp2(444)
#+end_src

* 3rd example

#+name: rp3
#+begin_src python -i -n :results silent :session
# chained.py example
def rp3(seed, args=None):
    import asyncio
    import random
    import time

    async def part1(n: int) -> str:
        i = random.randint(0, 10)
        print(f"part1({n}) sleeping for {i} seconds.")
        await asyncio.sleep(i)
        result = f"result{n}-1"
        print(f"Returning part1({n}) == {result}.")
        return result

    async def part2(n: int, arg: str) -> str:
        i = random.randint(0, 10)
        print(f"part2({n, arg}) sleeping for {i} seconds.")
        await asyncio.sleep(i)
        result = f"result{n}-2 derived from {arg}"
        print(f"Returning part2{n, arg} == {result}.")
        return result

    async def chain(n: int) -> None:
        start = time.perf_counter()
        p1 = await part1(n)
        p2 = await part2(n, p1)
        end = time.perf_counter() - start
        print(f"--> Chained result{n} => {p2} (took {end:0.2f} seconds).")

    async def main(*args):
        await asyncio.gather(*(chain(n) for n in args))


    random.seed(seed)
    args = [1, 2, 3] if args is None else args
    start = time.perf_counter()
    asyncio.run(main(*args))
    end = time.perf_counter() - start
    print(f"Program finished in {end:0.2f} seconds.")
#+end_src

#+begin_src python -i -n :results silent :session :tangle no
rp3(453, (3, 4, 2))
#+end_src

# Local Variables:
# fill-column: 80
# org-edit-src-content-indentation: 0
# End:
